export default RouterNames = {
  SEARCH_SCREEN: 'SearchScreen',
  NOTIFICATIONS: 'Notifications',
  ADVANCED_SEARCH: 'AdvangedSearch',
  APPOINTMENT_DETAILS: 'AppointmentDetails',
  CARD_DETAIL: 'CardDetail',
  HOMEPAGE: 'HomePage',
  LIST_SCREEN: 'ListScreen',
  LOGIN: 'login',
  SPLASH: 'Splash',
  SEE_ALL: 'SeeAll',
  CALENDAR: 'Calendar',
  CALENDAR1: 'Takvimim',
  SETTİNGS: 'MSettings',
  PROFILE: 'Profile',
  AGENDA:"Agenda",
  PLUS: 'Plus',
  FOR_APPOINTMENT: 'ForAppointment',
};
